name = "SpatialMultitaper"
uuid = "9e2dbb0b-aeb4-47f9-9d40-f5da6e8cc913"
authors = ["Jake Grainger"]
version = "0.0.4"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
BSplineKit = "093aae92-e908-43d7-9660-e50ee39d5a0a"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FINUFFT = "d8beea63-0952-562e-9c6a-8e8ef7364055"
GeoStatsProcesses = "aa102bde-5a27-4b0c-b2c1-e7a7dcc4c3e7"
GeoTables = "e502b557-6362-48c1-8219-d30d308dcdb0"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
BSplineKit = "0.19.0"
BenchmarkTools = "1.6.0"
ConstructionBase = "1.5.8"
Distributions = "0.25.113"
GeoStatsProcesses = "0.11.12"
GeoTables = "1.23.0"
HypergeometricFunctions = "0.3.28"
InvertedIndices = "1.3.0"
LazyArrays = "2.6.2"
Random = "1.11.0"
Reexport = "1.2.2"
SpecialFunctions = "2.4.0"
StaticArrays = "1.9.8"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
