[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
DocumenterMermaid = "a078cd44-4d9c-4618-b545-3ab9d77f9177"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeoStatsProcesses = "aa102bde-5a27-4b0c-b2c1-e7a7dcc4c3e7"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
SpatialMultitaper = "9e2dbb0b-aeb4-47f9-9d40-f5da6e8cc913"
